name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # ⚠️ Aquí apuntamos a la carpeta de tu módulo Maven: gestion-vuelos
        working-directory: gestion-vuelos

    steps:
      # 1. Clonar el repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configurar JDK 17 (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3. Compilar y Ejecutar Pruebas (Build and Test)
      - name: Build and Test
        run: mvn clean verify

      # 4. Análisis Checkstyle
      - name: Checkstyle Analysis
        run: mvn checkstyle:checkstyle
        continue-on-error: true

      # 5. Análisis PMD
      - name: PMD Analysis
        run: mvn pmd:check
        continue-on-error: true

      # 6. Generar reporte de cobertura con JaCoCo
      - name: Generate Coverage Report
        run: mvn jacoco:report

      # 7. Subir artefactos generados (XML)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Maven-Reports
          path: |
            # ⚠️ Ajustamos la ruta para que apunte a target/site de gestion-vuelos
            gestion-vuelos/target/site/jacoco/jacoco.xml
            gestion-vuelos/target/checkstyle-result.xml
            gestion-vuelos/target/pmd.xml
