name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # Aquí debe ir la carpeta EXACTA donde vive tu pom.xml
        working-directory: gestion-vuelos

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build and Test
        run: mvn clean verify

      - name: Checkstyle Analysis
        run: mvn checkstyle:checkstyle
        continue-on-error: true

      - name: PMD Analysis
        run: mvn pmd:check
        continue-on-error: true

      - name: Generate Coverage Report
        run: mvn jacoco:report

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Maven-Reports
          path: |
            # Las rutas a los archivos XML generados
            gestion-vuelos/target/site/jacoco/jacoco.xml
            gestion-vuelos/target/checkstyle-result.xml
            gestion-vuelos/target/pmd.xml
